In [2]:
pip install ucimlrepo

Requirement already satisfied: ucimlrepo in d:\arxius\anaconda\lib\site-packages (0.0.7)
Requirement already satisfied: pandas>=1.0.0 in d:\arxius\anaconda\lib\site-packages (from ucimlrepo) (2.3.3)
Requirement already satisfied: certifi>=2020.12.5 in d:\arxius\anaconda\lib\site-packages (from ucimlrepo) (2026.1.4)
Requirement already satisfied: numpy>=1.26.0 in d:\arxius\anaconda\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\arxius\anaconda\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\arxius\anaconda\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\arxius\anaconda\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in d:\arxius\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
from ucimlrepo import fetch_ucirepo 
  
 
heart_disease = fetch_ucirepo(id=45) 
  
X = heart_disease.data.features 
y = heart_disease.data.targets 
  

print(heart_disease.metadata) 
print(heart_disease.variables)

{'uci_id': 45, 'name': 'Heart Disease', 'repository_url': 'https://archive.ics.uci.edu/dataset/45/heart+disease', 'data_url': 'https://archive.ics.uci.edu/static/public/45/data.csv', 'abstract': '4 databases: Cleveland, Hungary, Switzerland, and the VA Long Beach', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 303, 'num_features': 13, 'feature_types': ['Categorical', 'Integer', 'Real'], 'demographics': ['Age', 'Sex'], 'target_col': ['num'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1989, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C52P4X', 'creators': ['Andras Janosi', 'William Steinbrunn', 'Matthias Pfisterer', 'Robert Detrano'], 'intro_paper': {'ID': 231, 'type': 'NATIVE', 'title': 'International application of a new probability algorithm for the diagnosis of coronary artery disease.', 'authors': 'R. Detrano, A. Jánosi, W. Steinbrunn, M. Pfisterer, J. Schmid, S. Sandhu, K. Guppy, S. Lee, V. Froelicher', 'venue': 'American Journal of Cardiology', 'year': 1989, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/a7d714f8f87bfc41351eb5ae1e5472f0ebbe0574', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': '2756873', 'pmcid': None}, 'additional_info': {'summary': 'This database contains 76 attributes, but all published experiments refer to using a subset of 14 of them.  In particular, the Cleveland database is the only one that has been used by ML researchers to date.  The "goal" field refers to the presence of heart disease in the patient.  It is integer valued from 0 (no presence) to 4. Experiments with the Cleveland database have concentrated on simply attempting to distinguish presence (values 1,2,3,4) from absence (value 0).  \n   \nThe names and social security numbers of the patients were recently removed from the database, replaced with dummy values.\n\nOne file has been "processed", that one containing the Cleveland database.  All four unprocessed files also exist in this directory.\n\nTo see Test Costs (donated by Peter Turney), please see the folder "Costs" ', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Only 14 attributes used:\r\n      1. #3  (age)       \r\n      2. #4  (sex)       \r\n      3. #9  (cp)        \r\n      4. #10 (trestbps)  \r\n      5. #12 (chol)      \r\n      6. #16 (fbs)       \r\n      7. #19 (restecg)   \r\n      8. #32 (thalach)   \r\n      9. #38 (exang)     \r\n      10. #40 (oldpeak)   \r\n      11. #41 (slope)     \r\n      12. #44 (ca)        \r\n      13. #51 (thal)      \r\n      14. #58 (num)       (the predicted attribute)\r\n\r\nComplete attribute documentation:\r\n      1 id: patient identification number\r\n      2 ccf: social security number (I replaced this with a dummy value of 0)\r\n      3 age: age in years\r\n      4 sex: sex (1 = male; 0 = female)\r\n      5 painloc: chest pain location (1 = substernal; 0 = otherwise)\r\n      6 painexer (1 = provoked by exertion; 0 = otherwise)\r\n      7 relrest (1 = relieved after rest; 0 = otherwise)\r\n      8 pncaden (sum of 5, 6, and 7)\r\n      9 cp: chest pain type\r\n        -- Value 1: typical angina\r\n        -- Value 2: atypical angina\r\n        -- Value 3: non-anginal pain\r\n        -- Value 4: asymptomatic\r\n     10 trestbps: resting blood pressure (in mm Hg on admission to the hospital)\r\n     11 htn\r\n     12 chol: serum cholestoral in mg/dl\r\n     13 smoke: I believe this is 1 = yes; 0 = no (is or is not a smoker)\r\n     14 cigs (cigarettes per day)\r\n     15 years (number of years as a smoker)\r\n     16 fbs: (fasting blood sugar > 120 mg/dl)  (1 = true; 0 = false)\r\n     17 dm (1 = history of diabetes; 0 = no such history)\r\n     18 famhist: family history of coronary artery disease (1 = yes; 0 = no)\r\n     19 restecg: resting electrocardiographic results\r\n        -- Value 0: normal\r\n        -- Value 1: having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of > 0.05 mV)\r\n        -- Value 2: showing probable or definite left ventricular hypertrophy by Estes\' criteria\r\n     20 ekgmo (month of exercise ECG reading)\r\n     21 ekgday(day of exercise ECG reading)\r\n     22 ekgyr (year of exercise ECG reading)\r\n     23 dig (digitalis used furing exercise ECG: 1 = yes; 0 = no)\r\n     24 prop (Beta blocker used during exercise ECG: 1 = yes; 0 = no)\r\n     25 nitr (nitrates used during exercise ECG: 1 = yes; 0 = no)\r\n     26 pro (calcium channel blocker used during exercise ECG: 1 = yes; 0 = no)\r\n     27 diuretic (diuretic used used during exercise ECG: 1 = yes; 0 = no)\r\n     28 proto: exercise protocol\r\n          1 = Bruce     \r\n          2 = Kottus\r\n          3 = McHenry\r\n          4 = fast Balke\r\n          5 = Balke\r\n          6 = Noughton \r\n          7 = bike 150 kpa min/min  (Not sure if "kpa min/min" is what was written!)\r\n          8 = bike 125 kpa min/min  \r\n          9 = bike 100 kpa min/min\r\n         10 = bike 75 kpa min/min\r\n         11 = bike 50 kpa min/min\r\n         12 = arm ergometer\r\n     29 thaldur: duration of exercise test in minutes\r\n     30 thaltime: time when ST measure depression was noted\r\n     31 met: mets achieved\r\n     32 thalach: maximum heart rate achieved\r\n     33 thalrest: resting heart rate\r\n     34 tpeakbps: peak exercise blood pressure (first of 2 parts)\r\n     35 tpeakbpd: peak exercise blood pressure (second of 2 parts)\r\n     36 dummy\r\n     37 trestbpd: resting blood pressure\r\n     38 exang: exercise induced angina (1 = yes; 0 = no)\r\n     39 xhypo: (1 = yes; 0 = no)\r\n     40 oldpeak = ST depression induced by exercise relative to rest\r\n     41 slope: the slope of the peak exercise ST segment\r\n        -- Value 1: upsloping\r\n        -- Value 2: flat\r\n        -- Value 3: downsloping\r\n     42 rldv5: height at rest\r\n     43 rldv5e: height at peak exercise\r\n     44 ca: number of major vessels (0-3) colored by flourosopy\r\n     45 restckm: irrelevant\r\n     46 exerckm: irrelevant\r\n     47 restef: rest raidonuclid (sp?) ejection fraction\r\n     48 restwm: rest wall (sp?) motion abnormality\r\n        0 = none\r\n        1 = mild or moderate\r\n        2 = moderate or severe\r\n        3 = akinesis or dyskmem (sp?)\r\n     49 exeref: exercise radinalid (sp?) ejection fraction\r\n     50 exerwm: exercise wall (sp?) motion \r\n     51 thal: 3 = normal; 6 = fixed defect; 7 = reversable defect\r\n     52 thalsev: not used\r\n     53 thalpul: not used\r\n     54 earlobe: not used\r\n     55 cmo: month of cardiac cath (sp?)  (perhaps "call")\r\n     56 cday: day of cardiac cath (sp?)\r\n     57 cyr: year of cardiac cath (sp?)\r\n     58 num: diagnosis of heart disease (angiographic disease status)\r\n        -- Value 0: < 50% diameter narrowing\r\n        -- Value 1: > 50% diameter narrowing\r\n        (in any major vessel: attributes 59 through 68 are vessels)\r\n     59 lmt\r\n     60 ladprox\r\n     61 laddist\r\n     62 diag\r\n     63 cxmain\r\n     64 ramus\r\n     65 om1\r\n     66 om2\r\n     67 rcaprox\r\n     68 rcadist\r\n     69 lvx1: not used\r\n     70 lvx2: not used\r\n     71 lvx3: not used\r\n     72 lvx4: not used\r\n     73 lvf: not used\r\n     74 cathef: not used\r\n     75 junk: not used\r\n     76 name: last name of patient  (I replaced this with the dummy string "name")', 'citation': None}}
        name     role         type demographic  \
0        age  Feature      Integer         Age
1        sex  Feature  Categorical         Sex
2         cp  Feature  Categorical        None
3   trestbps  Feature      Integer        None
4       chol  Feature      Integer        None
5        fbs  Feature  Categorical        None
6    restecg  Feature  Categorical        None
7    thalach  Feature      Integer        None
8      exang  Feature  Categorical        None
9    oldpeak  Feature      Integer        None
10     slope  Feature  Categorical        None
11        ca  Feature      Integer        None
12      thal  Feature  Categorical        None
13       num   Target      Integer        None

                                          description  units missing_values
0                                                None  years             no
1                                                None   None             no
2                                                None   None             no
3   resting blood pressure (on admission to the ho...  mm Hg             no
4                                   serum cholestoral  mg/dl             no
5                     fasting blood sugar > 120 mg/dl   None             no
6                                                None   None             no
7                         maximum heart rate achieved   None             no
8                             exercise induced angina   None             no
9   ST depression induced by exercise relative to ...   None             no
10                                               None   None             no
11  number of major vessels (0-3) colored by flour...   None            yes
12                                               None   None            yes
13                         diagnosis of heart disease   None             no

In [4]:
print(X.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        299 non-null    float64
 12  thal      301 non-null    float64
dtypes: float64(3), int64(10)
memory usage: 30.9 KB
None

In [5]:
print(X.head())

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3
1   67    1   4       160   286    0        2      108      1      1.5      2
2   67    1   4       120   229    0        2      129      1      2.6      2
3   37    1   3       130   250    0        0      187      0      3.5      3
4   41    0   2       130   204    0        2      172      0      1.4      1

    ca  thal
0  0.0   6.0
1  3.0   3.0
2  2.0   7.0
3  0.0   3.0
4  0.0   3.0

In [6]:
print(y.head(100))

    num
0     0
1     2
2     1
3     0
4     0
..  ...
95    1
96    2
97    3
98    0
99    0

[100 rows x 1 columns]

In [7]:
import pandas as pd

In [8]:
df = pd.concat([X, y], axis=1)

print(f"Final shape: {df.shape}")
print(df.head())

Final shape: (303, 14)
   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3
1   67    1   4       160   286    0        2      108      1      1.5      2
2   67    1   4       120   229    0        2      129      1      2.6      2
3   37    1   3       130   250    0        0      187      0      3.5      3
4   41    0   2       130   204    0        2      172      0      1.4      1

    ca  thal  num
0  0.0   6.0    0
1  3.0   3.0    2
2  2.0   7.0    1
3  0.0   3.0    0
4  0.0   3.0    0

In [9]:
df.shape

(303, 14)

In [10]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63,1,1,145,233,1,2,150,0,2.3,3,0.0,6.0,0
1,67,1,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2
2,67,1,4,120,229,0,2,129,1,2.6,2,2.0,7.0,1
3,37,1,3,130,250,0,0,187,0,3.5,3,0.0,3.0,0
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,3.0,0

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        299 non-null    float64
 12  thal      301 non-null    float64
 13  num       303 non-null    int64
dtypes: float64(3), int64(11)
memory usage: 33.3 KB

In [12]:
print(df['ca'].value_counts(dropna=False))

ca
0.0    176
1.0     65
2.0     38
3.0     20
NaN      4
Name: count, dtype: int64

In [13]:
print(df['thal'].value_counts(dropna=False))

thal
3.0    166
7.0    117
6.0     18
NaN      2
Name: count, dtype: int64

In [14]:
df['ca_is_null'] = df['ca'].isnull()

# 2. Comparem 'ca_is_null' amb la columna 'num'
print("--- Relació entre Nuls a 'ca' i la columna 'num' ---")
print(pd.crosstab(df['ca_is_null'], df['num']))

--- Relació entre Nuls a 'ca' i la columna 'num' ---
num           0   1   2   3   4
ca_is_null
False       161  54  36  35  13
True          3   1   0   0   0

In [15]:
df['thal_is_null'] = df['thal'].isnull()
print("\n--- Relació entre Nuls a 'thal' i la columna 'num' ---")
print(pd.crosstab(df['thal_is_null'], df['num']))

--- Relació entre Nuls a 'thal' i la columna 'num' ---
num             0   1   2   3   4
thal_is_null
False         163  55  35  35  13
True            1   0   1   0   0

In [16]:
df.dropna(subset=['thal'], inplace=True)

In [17]:
df.loc[(df['ca'].isnull()) & (df['num'] == 0), 'ca'] = 0.0

df['ca'] = df['ca'].fillna(1.0)

print("Nuls restants a 'ca':", df['ca'].isnull().sum())
print("Nuls totals al DF:", df.isnull().sum().sum())

Nuls restants a 'ca': 0
Nuls totals al DF: 0

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 301 entries, 0 to 302
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   age           301 non-null    int64
 1   sex           301 non-null    int64
 2   cp            301 non-null    int64
 3   trestbps      301 non-null    int64
 4   chol          301 non-null    int64
 5   fbs           301 non-null    int64
 6   restecg       301 non-null    int64
 7   thalach       301 non-null    int64
 8   exang         301 non-null    int64
 9   oldpeak       301 non-null    float64
 10  slope         301 non-null    int64
 11  ca            301 non-null    float64
 12  thal          301 non-null    float64
 13  num           301 non-null    int64
 14  ca_is_null    301 non-null    bool
 15  thal_is_null  301 non-null    bool
dtypes: bool(2), float64(3), int64(11)
memory usage: 35.9 KB

In [19]:
df['patient_id'] = range(1, len(df) + 1)

In [20]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num,ca_is_null,thal_is_null,patient_id
0,63,1,1,145,233,1,2,150,0,2.3,3,0.0,6.0,0,False,False,1
1,67,1,4,160,286,0,2,108,1,1.5,2,3.0,3.0,2,False,False,2
2,67,1,4,120,229,0,2,129,1,2.6,2,2.0,7.0,1,False,False,3
3,37,1,3,130,250,0,0,187,0,3.5,3,0.0,3.0,0,False,False,4
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,3.0,0,False,False,5

In [27]:
print(df.columns)

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num', 'ca_is_null',
       'thal_is_null', 'patient_id'],
      dtype='object')

In [32]:
heart_main = df.copy()
heart_main = heart_main.drop(columns=['ca_is_null', 'thal_is_null'], errors='ignore')

# 2. Movem el 'patient_id' al principi (posició 0)
# Primer el treiem i després l'inserim a la primera posició
cols = list(heart_main.columns)
if 'patient_id' in cols:
    cols.insert(0, cols.pop(cols.index('patient_id')))
    heart_main = heart_main[cols]

# 3. Renomenem les columnes categòriques a IDs
heart_main = heart_main.rename(columns={
    'sex': 'sex_id',
    'cp': 'cp_id',
    'fbs': 'fbs_id',
    'restecg': 'restecg_id',
    'slope': 'slope_id',
    'thal': 'thal_id',
    'num': 'diagnosis_id',
    'exang': 'exang_id'
})

print("Columnes actuals de heart_main:")
print(heart_main.columns)

Columnes actuals de heart_main:
Index(['patient_id', 'age', 'sex_id', 'cp_id', 'trestbps', 'chol', 'fbs_id',
       'restecg_id', 'thalach', 'exang_id', 'oldpeak', 'slope_id', 'ca',
       'thal_id', 'diagnosis_id'],
      dtype='object')

In [43]:
heart_main['thal_id'] = heart_main['thal_id'].replace({3: 1, 6: 2, 7: 3})

In [44]:
heart_main.head()

,patient_id,age,sex_id,cp_id,trestbps,chol,fbs_id,restecg_id,thalach,exang_id,oldpeak,slope_id,ca,thal_id,diagnosis_id
0,1,63,1,1,145,233,1,2,150,0,2.3,3,0.0,2.0,0
1,2,67,1,4,160,286,0,2,108,1,1.5,2,3.0,1.0,2
2,3,67,1,4,120,229,0,2,129,1,2.6,2,2.0,3.0,1
3,4,37,1,3,130,250,0,0,187,0,3.5,3,0.0,1.0,0
4,5,41,0,2,130,204,0,2,172,0,1.4,1,0.0,1.0,0

In [45]:
dim_sex = pd.DataFrame({
    'sex_id': [0, 1], 
    'sex_desc': ['Female', 'Male']
})

dim_cp = pd.DataFrame({
    'cp_id': [1, 2, 3, 4], 
    'cp_desc': ['Typical Angina', 'Atypical Angina', 'Non-anginal Pain', 'Asymptomatic']
})

dim_fbs = pd.DataFrame({
    'fbs_id': [0, 1], 
    'fbs_desc': ['<= 120 mg/dL', '> 120 mg/dL']
})

dim_restecg = pd.DataFrame({
    'restecg_id': [0, 1, 2], 
    'restecg_desc': ['Normal', 'ST-T abnormality', 'LV hypertrophy']
})

dim_exang = pd.DataFrame({
    'exang_id': [0, 1],
    'exang_desc': ['No exercise-induced angina', 'Exercise-induced angina'],
    'exang_risc': ['Low risk', 'High risk']
})

dim_slope = pd.DataFrame({
    'slope_id': [1, 2, 3], 
    'slope_desc': ['Upsloping', 'Flat', 'Downsloping']
})

dim_thal = pd.DataFrame({
    'thal_id': [1, 2, 3], 
    'thal_desc': ['Normal', 'Fixed defect', 'Reversible defect']
})

dim_target = pd.DataFrame({
    'diagnosis_id': [0, 1, 2, 3, 4], 
    'diagnosis_desc': ['Healthy', 'Stage 1', 'Stage 2', 'Stage 3', 'Stage 4']
})

print("All tables has been created correctly.")

All tables has been created correctly.

In [46]:
# --- FINAL STRUCTURE CHECK ---

# Display the main fact table
print("=== FACT TABLE: heart_main ===")
display(heart_main.head())

# Create a dictionary to iterate through all dimension tables
dimension_tables = {
    "Dimension: Sex": dim_sex,
    "Dimension: Chest Pain (CP)": dim_cp,
    "Dimension: Fasting Blood Sugar (FBS)": dim_fbs,
    "Dimension: Resting ECG": dim_restecg,
    "Dimension: Exercise Angina (Exang)": dim_exang,
    "Dimension: Slope": dim_slope,
    "Dimension: Thalassemia (Thal)": dim_thal,
    "Dimension: Diagnosis (Target)": dim_target
}

# Print headers and heads for each dimension table
for name, table in dimension_tables.items():
    print(f"\n=== {name} ===")
    display(table.head())

=== FACT TABLE: heart_main ===

,patient_id,age,sex_id,cp_id,trestbps,chol,fbs_id,restecg_id,thalach,exang_id,oldpeak,slope_id,ca,thal_id,diagnosis_id
0,1,63,1,1,145,233,1,2,150,0,2.3,3,0.0,2.0,0
1,2,67,1,4,160,286,0,2,108,1,1.5,2,3.0,1.0,2
2,3,67,1,4,120,229,0,2,129,1,2.6,2,2.0,3.0,1
3,4,37,1,3,130,250,0,0,187,0,3.5,3,0.0,1.0,0
4,5,41,0,2,130,204,0,2,172,0,1.4,1,0.0,1.0,0

=== Dimension: Sex ===

   sex_id sex_desc
0       0   Female
1       1     Male

=== Dimension: Chest Pain (CP) ===

   cp_id           cp_desc
0      1    Typical Angina
1      2   Atypical Angina
2      3  Non-anginal Pain
3      4      Asymptomatic

=== Dimension: Fasting Blood Sugar (FBS) ===

   fbs_id      fbs_desc
0       0  <= 120 mg/dL
1       1   > 120 mg/dL

=== Dimension: Resting ECG ===

   restecg_id      restecg_desc
0           0            Normal
1           1  ST-T abnormality
2           2    LV hypertrophy

=== Dimension: Exercise Angina (Exang) ===

   exang_id                  exang_desc exang_risc
0         0  No exercise-induced angina   Low risk
1         1     Exercise-induced angina  High risk

=== Dimension: Slope ===

   slope_id   slope_desc
0         1    Upsloping
1         2         Flat
2         3  Downsloping

=== Dimension: Thalassemia (Thal) ===

   thal_id          thal_desc
0        1             Normal
1        2       Fixed defect
2        3  Reversible defect

=== Dimension: Diagnosis (Target) ===

   diagnosis_id diagnosis_desc
0             0        Healthy
1             1        Stage 1
2             2        Stage 2
3             3        Stage 3
4             4        Stage 4

In [48]:
# --- FINAL EXPORT TO CSV (CLEANED DATA) ---

# 1. Export the Fact Table (The main table with patient data)
# This includes the patient_id, clinical measurements, and foreign keys (_id)
heart_main.to_csv('heart_main.csv', index=False)

# 2. Export all Dimension Tables (The lookup dictionaries)
# Make sure you have executed the thal_id remap (1, 2, 3) before this!
dim_sex.to_csv('dim_sex.csv', index=False)
dim_cp.to_csv('dim_cp.csv', index=False)
dim_fbs.to_csv('dim_fbs.csv', index=False)
dim_restecg.to_csv('dim_restecg.csv', index=False)
dim_exang.to_csv('dim_exang.csv', index=False)
dim_slope.to_csv('dim_slope.csv', index=False)
dim_thal.to_csv('dim_thal.csv', index=False)
dim_target.to_csv('dim_target.csv', index=False)

print("🚀 SUCCESS: All 9 CSV files have been exported and are ready for SQL!")

🚀 SUCCESS: All 9 CSV files have been exported and are ready for SQL!